### ISSUE TITLE
Compiling v1.2.0.1 fails

### ISSUE THREAD

**Issue by marec2000** [GlobalBoost/GlobalBoost-Y#10]
Seems that some moc files are missing in order to compile:

`make: *** No rule to make target 'build/buydomains.moc', needed by 'build/buydomains.o'.  Stop.`

**Comment by Infernoman** [comment]
I ran into a few of these while compiling, What i did was removed the '#include "buydomains.moc" ' from src/qt/buydomains.cpp

**Comment by marec2000** [comment]
I figured out that it also helps to put empty files with corresponding names into the build folder. Two examples just have been put there in the past.

**Comment by BlockchainDev727** [comment]
Hello
Now new source havent issue anymore.

:)
