### ISSUE TITLE
sync wallet 0 connections Win7 64

### ISSUE THREAD

**Issue by pekster85** [GlobalBoost/GlobalBoost-Y#16]
Hi, 
i downloaded the gui wallet for win64,
but it wont sync
and it says 0 connections at the bottom
Has firewalls permissions..
what am i missing?

**Comment by BlockchainDev727** [comment]
Hello Bro
I think it isnt firewall problem.
Maybe you missed live node for syncing.

Please add live node to conf.

addnode=76.74.170.38
addnode=69.90.132.249
addnode=47.133.226.128
addnode=208.180.220.104
addnode=80.30.208.101
addnode=47.133.226.128
addnode=95.219.240.28
addnode=178.238.236.130
addnode=173.212.200.25
addnode=13.209.101.186
addnode=35.162.166.109
addnode=167.114.249.196
addnode=85.14.242.77
addnode=94.23.0.56
addnode=217.103.221.7
addnode=34.231.68.33
addnode=192.99.19.160
addnode=35.170.29.92
addnode=34.202.104.227
addnode=94.72.32.201
addnode=34.233.223.15
addnode=34.225.224.198
addnode=195.201.176.91
addnode=203.198.146.232
addnode=108.170.1.134
addnode=173.212.214.96
addnode=5.189.182.109
addnode=74.96.199.207

:)
